
#-----------------------------------------------------------+
#           RVSAO Radial Velocity Analysis Package          |
#           Smithsonian Astrophysical Observatory           |
#                   Telescope Data Center                   |
#                 Version 2.8.2 May 2, 2014                 |
#                                                           |
#        *** Run rvrelearn to update parameters ***         |
#-----------------------------------------------------------+

